Jm 38 aws listeners package
janis-commerce/aws-listeners pull request #2
Opened 2020-06-23 23:07 UTC by manuelvilche

Ticket: [JM-38](https://fizzmod.atlassian.net/browse/JM-38)

Nuevo package en donde incluye algunos servicios de AWS para poder generar un listener

2020-06-24 17:09 UTC, gastonpereyra commented on README.md
> +for a more detailed explanation you can go to the following documents
La mayuscula al comenzar la oración

```suggestion
For a more detailed explanation you can go to the following documents
```

2020-06-24 17:14 UTC, gastonpereyra commented on docs/s3-listener.md
> +If you are working with serverless framework and want to use the serverless-s3-local plugin you need to config the enviroment variable S3_LOCAL_ENDPOINT
:bulb: Sugiero

```suggestion
If you are working with serverless framework and want to use the serverless-s3-local plugin, you need to config the enviroment variable `S3_LOCAL_ENDPOINT`
```

2020-06-24 17:40 UTC, gastonpereyra commented on docs/s3-listener.md
> +## S3Listener
:thinking: 

No repitería el mismo título que el princpial, pondría algo mas represantitvo de esta sección

```suggestion
## API
```

2020-06-24 17:41 UTC, gastonpereyra commented on docs/s3-listener.md
> +This is the class you should extend to code your own Listeners. You can customize them with the following methods and getters:
Acortaría esta descripción a
```suggestion
You can customize them with the following methods and getters:
```

2020-06-24 17:43 UTC, gastonpereyra commented on docs/s3-listener.md
> +
Aca agrearia la descripción que originalmente esta en otra sección:

```
You can manage S3 Listeners extending from this class.
```

2020-06-24 17:44 UTC, gastonpereyra commented on docs/s3-listener.md
> +This method is required, and should have the logic of your Listener.
Resaltaría `required`

```suggestion
This method is **REQUIRED**, and should have the logic of your Listener.
```

2020-06-24 17:45 UTC, gastonpereyra commented on docs/s3-listener.md
> +## S3ServerlessHandler
```suggestion
# S3ServerlessHandler
```

2020-06-24 17:46 UTC, gastonpereyra commented on docs/s3-listener.md
> +
Agregaria el sub-títutlo 

```
## Method
```

2020-06-24 17:49 UTC, gastonpereyra commented on docs/sns-listener.md
> +This is the class you should extend to code your own Listeners. You can customize them with the following methods and getters:
Algo parecido a `docs/s3-listner.md`
```suggestion
This is the class you should extend to code your own Listeners. 

## API
You can customize them with the following methods and getters:
```

2020-06-24 17:50 UTC, gastonpereyra commented on docs/sns-listener.md
> +This method is required, and should have the logic of your Listener.
Resaltaría `required`
```suggestion
This method is **REQUIRE**, and should have the logic of your Listener.
```

2020-06-24 17:50 UTC, gastonpereyra commented on docs/sns-listener.md
> +## SNSServerlessHandler
```suggestion
# SNSServerlessHandler
```

2020-06-24 17:51 UTC, gastonpereyra commented on docs/sns-listener.md
> +
Agregaría

```
## Methods
```

2020-06-24 17:54 UTC, gastonpereyra commented on docs/sqs-listener.md
> +# SQSlisteners
Lo mismo que los otros Docs:

- Pasaria la descripción general del listener para arriba, antes de las configuración
- CLOUDWATCH_PREFIX -> `CLOUDWATCH_PREFIX` que resalté como un code
- La parte de la customización le pondria como título `## API`
- Resaltaría la palabra REQUIRED
- Pondría `## SQSServerlessHandler` como `# SQSServerlessHandler` y agregaria el sub-titulo `## Methods`

2020-06-24 18:43 UTC, gastonpereyra commented on lib/s3/serverless/dispatcher.js
> +		if(typeof event !== 'object' || !Object.keys(event).length)
:thinking:  Talvés se podría aprovechar la función que valida que sea un objeto

```suggestion
		if(!isObject(event) || !Object.keys(event).length)
```

2020-06-24 18:46 UTC, gastonpereyra commented on lib/s3/serverless/dispatcher.js
> +const isObject = value => typeof value === 'object' && !Array.isArray(value);
:bulb:  Usas esta validación en varias ocaciones (x ejemplo `modules/cloudwatch-logs/events.js`). Talvés podrias hacerla "helper" en un archivo aparte y usarla para no repetir código

2020-06-24 18:48 UTC, gastonpereyra commented on lib/s3/serverless/dispatcher.js
> +const isObject = value => typeof value === 'object' && !Array.isArray(value);
Es más hay otra validación que usas mucho que es la de objeto-no-vacia, esa tmb podrias ponerla en otro archivo y aprovechar esos helpers

2020-06-24 18:51 UTC, gastonpereyra commented on lib/sqs/sqs-listener.js
> +			attributes.MessageAttributes.logId = { DataType: 'String',	StringValue: this.logId };
Quedó un TAB en lugar de Espacio

2020-06-24 18:52 UTC, gastonpereyra requested changes
Dejó un par de comentarios

2020-06-26 20:06 UTC, gastonpereyra approved these changes

2020-07-01 15:23 UTC, jormaechea requested changes

2020-07-01 15:23 UTC, jormaechea commented on lib/s3/s3-listener.js
> +	get fileExtention() {
```suggestion
	get fileExtension() {
```
Acá y en todos lados donde se usa..

2020-07-01 15:23 UTC, jormaechea commented on lib/s3/s3-listener.js
> +	get filename() {
```suggestion
	get fileName() {
```
Me perturba que sean todos camelCase menos este y `fileSize`. Ajustate esos dos...

2020-07-01 15:23 UTC, jormaechea commented on lib/sns/serverless/dispatcher.js
> +			this._event = { ...JSON.parse(Message) };
```suggestion
			this._event = JSON.parse(Message);
```

2020-07-01 15:23 UTC, jormaechea commented on lib/sns/sns-listener.js
> +	get destinationRecipients() {
Tal como hablamos, todo lo que sea específico de `mail`, se tiene que ir..
Y hay que dejar getters más genéricos para acceder al _Record_ de SNS..

2020-07-01 15:23 UTC, jormaechea commented on lib/sqs/log/event.js
> +		return 'emitted';
Polémico es poco.. jaja Muy de eventos esto...

2020-08-12 17:08 UTC, jormaechea approved these changes
:rocket:

2020-08-12 17:09 UTC, merged